```{r setup, include = FALSE}
knitr::opts_chunk$set(message = F, 
                      error = F, 
                      warning = F)

```

# Week 10 {-} 
<div style = "font-size: 28pt"> **_Modern coexistence theory & Lotka-Volterra model of predator-prey interactions (1)_**</div>

## Lecture in a nutshell {-}

* **Topic:**
    1. 
    2. 
    3. 
    
<div style="height:1px ;"><br></div>

* **Topic:**
    1. 
    2. 
    3.

<div style="height:1px ;"><br></div>    
<br>


## Lab demonstration {-}

```{r, fig.width = 5, fig.height = 3.5, out.width = "70%", fig.align = "center", eval=FALSE}
library(tidyverse)
library(deSolve)

### Model specification
LV_competition_model <- function(times, state, parms) {
  with(as.list(c(state, parms)), {
    dN1_dt = N1*(r1-a11*N1-a12*N2)  
    dN2_dt = N2*(r2-a22*N2-a21*N1)
    return(list(c(dN1_dt, dN2_dt)))
  })
}


#### (2) Write down model 
LV_model <- function(times, state, parms) {
  with(as.list(c(state, parms)), {
    dN_dt = r * N - a * N * P
    dP_dt = e * a * N * P - d * P
    return(list(c(dN_dt, dP_dt)))  
  })
}

#### (3) Specify parameters Model application
Times <- seq(0, 50, by = 0.01)  
State <- c(N = 10, P = 2)  
Parms <- c(r = 1.0, a = 0.1, e = 0.8, d = 0.5)






### Model parameters
times <- seq(0, 100, by = 0.1)
state <- c(N1 = N1_0, N2 = N2_0)
parms <- c(r1 = r1, r2 = r2, a11 = a11, a21 = a21, a22 = a22, a12 = a12)

### Model application
pop_size <- ode(func = LV_competition_model, times = times, y = state, parms = parms)

### Visualize the population dynamics
pop_size %>%
  as.data.frame() %>%
  pivot_longer(cols = -time, names_to = "species", values_to = "N") %>%
  ggplot(aes(x = time, y = N, color = species)) + 
  geom_line(size = 1.5) +
  theme_classic(base_size = 12) +
  labs(x = "Time", y = "Population size") +
  scale_x_continuous(limits = c(0, 100.5), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0, max(pop_size)*1.2), expand = c(0, 0)) +
  scale_color_brewer(name = NULL, palette = "Set1")



### pop trajectory

### shinny app


```
<br>

## Additional readings {-}

[Signs of stabilisation and stable coexistence](./Additional readings/Broekman_et_al_2019_Eco_Let.pdf){target="_blank"}
<br>

## Assignments {-}

[](./Assignments/.pdf){target="_blank"}


